### ISSUE TITLE
Add table_size

### ISSUE THREAD

**Issue by IonicaBizau** [Bloggify/sequelize-datatable-views#5]
Add the `table_size` option. By default `"normal"` and it can be also `small`.

This will make the table smaller:

 - Add the `table-sm` class to the table
 - Apply the following CSS:

   ```css
    table.table.table-bordered.bg-white.table-sm {
        font-size: 12px;
    }

    table.table.table-sm button.btn-sm {
        font-size: 10px;
        padding: 3px 10px;
    }
    ```
